#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

print_ln("  _____ _    _       _______ _____  _    _ _____  " . "\n" . " / ____| |  | |   /\|__   __|  __ \| |  | |  __ \ "
    . "\n" . "| |    | |__| |  /  \  | |  | |__) | |__| | |__) |" . "\n" . "| |    |  __  | / /\ \ | |  |  ___/|  __  |  ___/ " . "\n"
    . "| |____| |  | |/ ____ \| |  | |    | |  | | |     " . "\n" . " \_____|_|  |_/_/    \_\_|  |_|    |_|  |_|_|     ", 1);

print_ln("\e[35mCHATPHP" . " \e[39mVersion \e[33m1.0 \e[32m" . date('Y-m-d H:i'), 1);


//1. chat
//2. history
//3. db-clear
//4. migrate

